$('.industry-slider').owlCarousel({
    loop:true,
    margin:30,
    dots:true,
    responsiveClass:true,
    responsive:{
        0:{
            items:1
        },
        450:{
            items:2
        },
        900:{
            items:4
        }
    }
});

$('.company-slider').owlCarousel({
    loop:true,
    margin:60,
    navText: [],
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:true
        },
        600:{
            items:3,
            nav:false
        },
        1000:{
            items:5,
            nav:true,
            loop:false
        }
    }
});

$('.project-slider').owlCarousel({
    loop:true,
    margin:30,
    dots:true,
    responsiveClass:true,
    responsive:{
        0:{
            items:1
        },
        450:{
            items:1
        },
        900:{
            items:1
        }
    }
})